# -*- coding: utf-8 -*-
"""ml-leakage-pipeline-Gangeswara.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ta7galaruKFD7Bc6icSoQ0VQzZXUOpDZ
"""

from sklearn.datasets import make_classification
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

# Data
X, y = make_classification(n_samples=1000, n_features=10, random_state=42)

# WRONG: scaling before split
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Model
model = LogisticRegression()
model.fit(X_train, y_train)

# Accuracy
train_acc = model.score(X_train, y_train)
test_acc = model.score(X_test, y_test)

print("Train Accuracy:", train_acc)
print("Test Accuracy:", test_acc)

"""Problem (Important)
Data leakage nadakuthu
Scaling pannumbothu test data info already use pannirukom
Mean & std full dataset la calculate pannirukom
Model future data ah already paathutu train aagudhu

Result:

Test accuracy over optimistic / fake hig
"""

from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import make_classification

# Data
X, y = make_classification(n_samples=1000, n_features=10, random_state=42)

# Split FIRST
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Pipeline
pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('model', LogisticRegression())
])

# Cross Validation
scores = cross_val_score(pipeline, X_train, y_train, cv=5)

print("Mean Accuracy:", scores.mean())
print("Std Dev:", scores.std())

"""Why this is correct?
Scaling happens inside each fold
Test data never leaks into training
Proper ML workflow
"""

from sklearn.tree import DecisionTreeClassifier

depths = [1, 5, 20]
results = []

for d in depths:
    model = DecisionTreeClassifier(max_depth=d, random_state=42)
    model.fit(X_train, y_train)

    train_acc = model.score(X_train, y_train)
    test_acc = model.score(X_test, y_test)

    results.append((d, train_acc, test_acc))

# Print table
print("Depth | Train Acc | Test Acc")
for r in results:
    print(r)